CREATE DATABASE IF NOT EXISTS coaching;
USE coaching;

DROP TABLE IF EXISTS VIDEOLIST, TEAMLIST, VIDEO, ROLE, PERSON, TEAM, SPORT;

CREATE TABLE SPORT
(
  SportID INT PRIMARY KEY AUTO_INCREMENT,
  SportName VARCHAR(25) NOT NULL
);

CREATE TABLE TEAM
(
  TeamID INT PRIMARY KEY AUTO_INCREMENT,
  SportID INT,
  Name VARCHAR(35) NOT NULL,
  CONSTRAINT FK_Team_Sport FOREIGN KEY (SportID) REFERENCES SPORT(SportID)
);

CREATE TABLE PERSON
(
  PersonID INT PRIMARY KEY AUTO_INCREMENT,
  FullName VARCHAR(25) NOT NULL,
  Dob DATE,
  Address VARCHAR(40),
  City VARCHAR(15),
  State VARCHAR(5),
  Phone VARCHAR(12),
  Email VARCHAR(35)
);

CREATE TABLE ROLE
(
  RoleID INT PRIMARY KEY AUTO_INCREMENT,
  RoleTitle VARCHAR(15) NOT NULL
);

CREATE TABLE VIDEO
(
  VideoID INT PRIMARY KEY AUTO_INCREMENT,
  Description VARCHAR(20) NOT NULL,
  Private CHAR NOT NULL,
  Location VARCHAR(50) NOT NULL,
  Category1 VARCHAR(10) NOT NULL,
  Category2 VARCHAR(10),
  Category3 VARCHAR(10),
  Title VARCHAR(25)
);

CREATE TABLE TEAMLIST
(
  Username VARCHAR(25) PRIMARY KEY,
  Password VARCHAR(12) NOT NULL,
  TeamID INT,
  PersonID INT,
  RoleID INT,
  CONSTRAINT FK_TEAMLIST_TEAM FOREIGN KEY (TeamID) REFERENCES TEAM(TeamID),
  CONSTRAINT FK_TEAMLIST_PERSON FOREIGN KEY (PersonID) REFERENCES PERSON(PersonID),
  CONSTRAINT FK_TEAMLIST_ROLE FOREIGN KEY (RoleID) REFERENCES ROLE(RoleID)
 );

CREATE TABLE VIDEOLIST
(
  VideoID INT,
  Username VARCHAR(25),
  StopPoint DECIMAL(8,8),
  Reason VARCHAR(200),
  CONSTRAINT FK_VIDEOLIST_VIDEO FOREIGN KEY (VideoID) REFERENCES VIDEO(VideoID),
  CONSTRAINT FK_VIDEOLIST_TEAMLIST FOREIGN KEY (Username) REFERENCES TEAMLIST(Username)
);

INSERT INTO SPORT(SportName) VALUES('Tennis');
INSERT INTO SPORT(SportName) VALUES('AFL');
INSERT INTO SPORT(SportName) VALUES('Basketball');
INSERT INTO SPORT(SportName) VALUES('Netball');
INSERT INTO SPORT(SportName) VALUES('Soccer');

INSERT INTO ROLE(RoleTitle) VALUES('Admin');
INSERT INTO ROLE(RoleTitle) VALUES('Coach');
INSERT INTO ROLE(RoleTitle) VALUES('Player');

INSERT INTO TEAM(SportID, Name) VALUES (2, 'Rockets');

INSERT INTO PERSON(FullName, Dob, Address, City, State, Phone, Email) VALUES ('John Doe', '1985-2-20', '123 Somewhere St', 'Some Place', 'VIC', '0412 345 6789', 'jdoe@test.com');
  
  
